config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'admin/homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
    end
    
    def show
    end
    
    def edit
    end
    
    def update
    end
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
    end
    
    def create
    end
    
    def edit
    end
    
    def update
    end
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
    end
    
    def show
    end
    
    def new
    end
    
    def create
    end
    
    def edit
    end
    
    def update
    end
    
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
    def update
    end
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    def show
    end
 
    def update
    end
    
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
    def new
    end
    
    def create
    end
    
    def destroy
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<h1>TOP</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
    　<li>
    　  商品一覧
    　</li>
    　
    　<li>
    　  会員一覧
    　</li>
    　
    　<li>
    　  注文履歴一覧
    　</li>
    　
    　<li>
    　  ジャンル一覧
    　</li>
    　
      <li>
        ログアウト
      </li>
    <% else %>
      <li>
        About
      </li>
      
      <li>
        商品一覧
      </li>
      
      <li>
        新規登録
      </li>
      
      <li>
        ログイン
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>